---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/people":
    post:
      summary: Creates a person
      tags:
        - People
      parameters: [ ]
      responses:
        '201':
          description: person created
          content: { }
        '422':
          description: invalid request
          content: { }
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                birth_date:
                  type: string
              required:
                - first_name
                - last_name
                - birth_date
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
